addons:
    apt:
        packages:
            - cmake
            - cpanminus
            - gcc
            - libperl-dev
            - librecode-dev
            - perl
            - make
            - valgrind
os: linux
dist: xenial
before_install:
    - sudo cpanm File::Find::Object IO::All List::Util Test::Differences Test::RunValgrind
script:
    - "mkdir B && cd B && cmake ../fortune-mod && make && make check && cd .."
    - "rm -fr B"
