addons:
    apt:
        packages:
            - cmake
            - cpanminus
            - gcc
            - libperl-dev
            - librecode-dev
            - perl
            - make
            - valgrind
            - xz-utils
            - zip
os: linux
dist: bionic
before_install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm Code::TidyAll::Plugin::Flake8 Code::TidyAll::Plugin::TestCount File::Find::Object List::Util Path::Tiny Perl::Critic Perl::Tidy Test::Code::TidyAll Test::Differences Test::RunValgrind
install: []
language: perl
script:
    - "export FORTUNE_TEST_TIDY=1"
    - "perl CI-testing/continuous-integration-testing.pl"
    - "rm -fr B"
sudo: false
