addons:
    apt:
        packages:
            - cmake
            - cpanminus
            - gcc
            - libperl-dev
            - librecode-dev
            - perl
            - make
            - valgrind
os: linux
dist: xenial
before_install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm File::Find::Object List::Util Path::Tiny Test::Differences Test::RunValgrind
install: []
language: perl
script:
    - "mkdir B && cd B && cmake ../fortune-mod && make && make check && cd .."
    - "rm -fr B"
sudo: false
